#!/bin/sh
set -u
mkdir -p "$HOME/.var/container/onlyoffice"
pakstak run onlyoffice \
	-- \
	--share-net \
	--gid 1000 \
	--uid 1000 \
	--hostname localhost \
	--bind "$HOME/.var/container/onlyoffice" /home/user \
	--dev-bind /dev/dri /dev/dri \
	--ro-bind /sys /sys \
	--tmpfs /run \
	--dir /run/user/1000/pulse \
	--ro-bind "$XDG_RUNTIME_DIR/pulse/native" /run/user/1000/pulse/native \
	--ro-bind /tmp/.X11-unix /tmp/.X11-unix \
	--ro-bind /etc/resolv.conf /etc/resolv.conf \
	--setenv HOME /home/user \
	--setenv DISPLAY "$DISPLAY" \
	--setenv XDG_RUNTIME_DIR /run/user/1000 \
	--chdir /home/user \
	/usr/bin/onlyoffice-desktopeditors
